# Generated by Django 3.0.4 on 2020-03-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_slug', models.SlugField()),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wiki.Category')),
            ],
        ),
    ]
