# Generated by Django 3.0.4 on 2020-03-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_slug',
            field=models.SlugField(editable=False),
        ),
    ]
